before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: YejPzzjybSZ4ez4IhFLRyUq1RNm2f/R2oLOwOLzq4Fst2m3HAIaFEa5Rz7wAa258RazO+mRu7cwaosiLAKjveylx2783hDNRR/4RGqElza8tMFlQX4vXgK80fr/G782HGmeHD5a+QyTicyhhDIwB5exSD4ffESp5FuEqWoG/Jgx+fAOnOz3TEwWti6r6F0NI9H27XGDxmpKlrwHEm7GP06nbhLWeHSf5DuTmUGehwPkXxSpR0/as58M+m6w8De9USMC5p6pWJI0F9GokwYIMyrhdWL7Z9xFgUItdRvcNoIivT4Ablbv2dd+fa5Gvl9N5jDn2riO5UQhzKeeY4v6juNnNZzWZxMmNtSdHsEK8OvYqIOO1nXvD5jEeb0oeI9Yt6ZRu2wE8tX/4tFPj/HU5uPUVXBg15I6zH7G1XE2suJKHUAdyZg/BuFfl/yBTZrR4ds55bM9kbTGfJbAJQGjyMPerfC+zCuEMjjeBa5eG+ygZ6TdkfJWjsnQ2ENuJLK03jFSFviMl1ZLprmbGXpaRfaKpGZHAY2p/sTg1WuFpj8BQbiLQvQT6q4E7wPLEPFNk9LiuCFPHlfSv+fIqn+pUxOnkkZ7gcKSmW9Oan9pS5a4U5wxYiXSpp7Xh8ubcXQCNKthdmxrd5giJ8TwNo5SaRCTZLlZvsZvr1hwSY3zxLIY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
